# Generated by Django 6.0.5 on 2026-05-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
