# Generated by Django 6.0.5 on 2026-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_booking_cancel_reason_vehicle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
