# Generated by Django 4.2.30 on 2026-05-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_fuellog_status_fuellog_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuellog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fuellog',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
