
# Generated by Django 6.0.5 on 2026-05-27 03:03

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_remove_fuellog_status_remove_fuellog_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission fee deducted from this booking.', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
