# Generated by Django 6.0.5 on 2026-05-27 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_booking_commission_fee_driver_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net amount earned by driver after commission.', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fare paid by passenger (fare_per_seat × seats).', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative net earnings of the driver (after commission).', max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Admin commission rate (10% - 30%).', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='fare_per_seat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fare charged per seat for this trip.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin commission deducted from total fare.', max_digits=10),
        ),
    ]
