# Generated by Django 6.0.5 on 2026-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_booking_driver_earnings_booking_total_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of credit/debit card.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='GCash or Maya mobile number.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya (PayMaya)'), ('credit_card', 'Credit / Debit Card')], help_text='Payment method chosen by the customer.', max_length=20, null=True),
        ),
    ]
