# Generated by Django 6.0.5 on 2026-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_booking_card_last4_booking_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Automatically set to paid when booking is completed.', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='fare_approved',
            field=models.BooleanField(default=False, help_text="Set to True by admin to approve driver's suggested fare."),
        ),
        migrations.AddField(
            model_name='trip',
            name='suggested_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Fare suggested by driver. If set, this overrides admin's base fare.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fare paid by passenger (effective_fare × seats).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fare_per_seat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base fare per seat set by admin.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('bus', 'Bus'), ('truck', 'Motor'), ('van', 'Van'), ('car', 'Car')], default='bus', max_length=50),
        ),
    ]
