# Generated by Django 6.0.5 on 2026-05-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_booking_payment_status_trip_fare_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cash_received_by',
            field=models.CharField(blank=True, help_text='Sino ang nakatanggap ng cash payment (e.g., Driver, Conductor).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya (PayMaya)'), ('credit_card', 'Credit / Debit Card')], help_text='Payment method chosen by the customer.', max_length=20, null=True),
        ),
    ]
