# Generated by Django 6.0.5 on 2026-05-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_booking_cash_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance ng trip sa kilometers.', max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='rate_per_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presyo per kilometer (set by admin).', max_digits=8),
        ),
    ]
