# Generated by Django 6.0.5 on 2026-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_trip_distance_km_trip_rate_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude ng customer.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, default='', help_text='Address ng pickup location ng customer.', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude ng customer.', null=True),
        ),
    ]
