# Generated by Django 6.0.5 on 2026-05-29 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_booking_pickup_latitude_booking_pickup_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time_slot', models.CharField(choices=[('06:00', '6:00 AM'), ('10:00', '10:00 AM'), ('13:00', '1:00 PM'), ('16:00', '4:00 PM'), ('18:00', '6:00 PM'), ('22:00', '10:00 PM')], max_length=5)),
                ('fare_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
            options={
                'ordering': ['time_slot'],
            },
        ),
    ]
